### ISSUE TITLE
Report profiling for unnamed components

### ISSUE THREAD

**Issue by shaine** [electrode-io/electrode-react-ssr-caching#8]
Hello,

When a component is unnamed, it doesn't end up showing in the profiling report. In my case, react-router's RouterContext component (which renders almost the entire component tree) doesn't seem to have a name, so the profiling report was missing almost all of my elements.

After digging, I found that a lack of `_name` on a component causes timing data to fail to end up inside the profiling object. A possible solution is to add `|| '(no name)'` to the end of the name setter at
https://github.com/electrode-io/electrode-react-ssr-caching/blob/master/lib/ssr-caching.js#L157

**Comment by jchip** [comment]
When profiling, generally, you should be profiling the rendering of your component in a loop directly, and not involving react-router.

It's also not useful to report any timing for component w/o names because the data is not useful to you.

The timing for a component will include sub timing of its children, so even if a component w/o name is not reported, its children would be reported, and they probably are more interesting to you.

**Comment by markudevelop** [comment]
@jchip if the profiling doesn't report the components names does it means it will also won't cache them? 

I have just profiled directly without routerContext and I was able to see the full list but will it work when I add it back up? 

Thanks

**Comment by wbyoung** [comment]
I ended up here after having the same experience. It seems as though it'd be valuable to support this (perhaps behind an option) as it would allow getting a full picture of what's going on when you do use modules such as `react-router` in server side rendering.

**Comment by wbyoung** [comment]
Trying to make this work following @jchip's advice of just rendering the component directly for profiling proved to be a little too difficult with a Relay application using server side rendering since just extracting the necessary props to render the component tree is (without using internal knowledge that I don't have at this point) non-trivial since Relay explicitly hides props from each component.

The following hack was easier to add:

```js
// file: electrode-profile-patch.js

import ReactCompositeComponent from 'react-dom/lib/ReactCompositeComponent';

const construct = ReactCompositeComponent.construct;

ReactCompositeComponent.construct = function (element) {
  const type = element.type;
  const name = type && typeof type !== "string" && (
    type.displayName || type.name || 'unknown'
  );

  (Object: any).defineProperty(this, '_name', {
    get: () => name,
    set: () => {},
  });

  return construct.call(this, element);
};
```

```js
// file: server.js

import 'electrode-react-ssr-caching'; // must be before react is imported
import './electrode-profile-patch';

import SSRCaching from 'electrode-react-ssr-caching';

// ...

        for (let i = 0; i < 10; i++) { ReactDOMServer.renderToString(router); }
        SSRCaching.clearProfileData();
        SSRCaching.enableProfiling();
  
        const reactOutput =
          ReactDOMServer.renderToString(router);
  
        SSRCaching.enableProfiling(false);
        console.log(JSON.stringify(SSRCaching.profileData, null, 2));

// ...
```
